name: COVID-19 Tracker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Install the dependencies
        run: npm install
      - name: Build the React Application
        run: npm run build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build/ wet-cabbage.surge.sh --token ${{ secrets.DEPLOYMENT_TOKEN }}
